project:
  type: website
  output-dir: docs

website:
  title: "Kuempel Conservation Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - people.qmd
      - data.qmd
      - teaching.qmd
      - media.qmd
      - contact.qmd
    
format:
  html:
    theme: yeti
    css: styles.css
    toc: true



