project:
  type: website
  output-dir: docs

website:
  title: "Dr Caitie Kuempel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - text: "People"
        file: people.qmd
      - teaching.qmd
      - contact.qmd
    
format:
  html:
    theme: yeti
    css: styles.css
    toc: true



