---
title: "Teaching"
editor: visual
---

# [3033ENV Environmental Data Analytics](https://www.griffith.edu.au/study/courses/environmental-data-analytics-3033ESC#trimester-2-nathan-campus)

This course will cover analysing large environmental datasets through multivariate statistics, spatial modelling techniques such as habitat suitability mapping, and data visualisation methods. It will also cover finding environmental datasets and preparing them for analysis. Students will be provided with opportunities for hands-on practice of these skills every week. They will also deepen their knowledge of the R language, as this course will be taught using R and RStudio. This course aims to prepare students for becoming environmental professionals, or researchers, working on environmental management issues using highly sought-after quantitative skills.

# [3804ENV Marine Ecosystem Modelling](https://www.griffith.edu.au/study/courses/marine-ecosystem-modelling-3804ENV#trimester-1-gold-coast-campus)

This course will provide students with the knowledge and quantitative skills needed for the management and conservation of marine living resources. Students will learn about the modelling methods that inform ecosystem management. Students will utilise the R programming environment to simulate the processes that determine marine ecosystem population dynamics. Prerequisite: Student must have completed 160CP.
